name: Get event payload

on:
  pull_request_target:
    types:
      - unlabeled

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: event
          path: ${{ github.event_path }}
