name: Remove `bug` labels

on:
  workflow_run:
    workflows:
      - CI

env:
  GH_REPO: ${{ github.repository }}
  GH_NO_UPDATE_NOTIFIER: 1
  GH_PROMPT_DISABLED: 1

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    strategy:
      matrix:
        PR: ${{ github.event.workflow_run.pull_requests.*.number }}
      fail-fast: false
    permissions:
      pull-requests: write # for `gh pr edit`
    steps:
      - name: Remove `bug` label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ matrix.PR }}
        run: gh pr edit "$PR" --remove-label bug
