name: Track approved PRs

on:
  pull_request_review:
    types: [submitted]

jobs:
  record_pull_number:
    runs-on: ubuntu-latest
    steps:
      - name: Save pull request number
        run: |
          mkdir -p pr
          echo '${{ github.event.pull_request.number }}' > pr/number

      - uses: actions/upload-artifact@v3
        with:
          name: pull_number
          path: pr

