name: CI
on: push

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest]
    container:
      image: ${{ matrix.runner == 'ubuntu-latest' && 'ghcr.io/homebrew/ubuntu22.04:main' || '' }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true

      - name: Set environment variables
        run: |
          echo "HOMEBREW_NO_AUTO_UPDATE=1" >>"${GITHUB_ENV}"
          echo "HOMEBREW_NO_INSTALL_FROM_API=1" >>"${GITHUB_ENV}"
          echo "HOMEBREW_DEVELOPER=1" >>"${GITHUB_ENV}"

      - run: brew config

      - run: brew doctor
        continue-on-error: true

      - run: brew ruby -e 'puts "hello"'

      - run: brew update

      - run: brew install bulk_extractor

      - run: brew linkage bulk_extractor

      - run: brew test bulk_extractor
