name: CI
on: [push, pull_request]

env:
  HOMEBREW_NO_INSTALL_FROM_API: 1

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@master

      - run: brew uninstall --force --ignore-dependencies glib

      - run: brew install --build-from-source glib

      - run: brew install pygobject3

      - run: /opt/homebrew/bin/python3 -c "from gi.repository import GLib"
