name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install `hyperfine` for benchmarking
        run: brew install hyperfine

      - name: Install LLVM to audit
        run: brew install llvm

      - name: Time LLVM audit
        run: |
          hyperfine --warmup 1 --export-markdown llvm_orig.md --ignore-failure 'brew audit llvm'
          printf '### LLVM, before:\n' >> "$GITHUB_STEP_SUMMARY"
          cat llvm_orig.md >> "$GITHUB_STEP_SUMMARY"
          printf '\n\n-----\n\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Time tap_syntax test
        run: |
          hyperfine --warmup 1 --export-markdown tap_syntax_orig.md --ignore-failure 'brew audit --tap=homebrew/core --except=version'
          printf '### Tap Syntax, before:\n' >> "$GITHUB_STEP_SUMMARY"
          cat tap_syntax_orig.md >> "$GITHUB_STEP_SUMMARY"
          printf '\n\n-----\n\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Fetch GCC audit PR
        run: |
          git config --global user.email "30379873+carlocab@users.noreply.github.com"
          git config --global user.name "Carlo Cabrera"
          pushd "$(brew --repository)"
          git fetch origin pull/13648/head:gcc
          git cherry-pick 4302af67b7e4e772342449fb888bcf4f3595d60c 718cf8b0df5666001dce4fa73a88c70218b98252
          popd

      - name: Time LLVM audit
        run: |
          hyperfine --warmup 1 --export-markdown llvm_new.md --ignore-failure 'brew audit llvm'
          printf '### LLVM, after:\n' >> "$GITHUB_STEP_SUMMARY"
          cat llvm_new.md >> "$GITHUB_STEP_SUMMARY"
          printf '\n\n-----\n\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Time tap_syntax test
        run: |
          hyperfine --warmup 1 --export-markdown tap_syntax_new.md --ignore-failure 'brew audit --tap=homebrew/core --except=version'
          printf '### Tap Syntax, after:\n' >> "$GITHUB_STEP_SUMMARY"
          cat tap_syntax_new.md >> "$GITHUB_STEP_SUMMARY"
          printf '\n\n-----\n\n' >> "$GITHUB_STEP_SUMMARY"
