name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: 'Homebrew/homebrew-core'
          fetch-depth: 0

      - env:
          BOTTLE_LINE_REGEX: '^\s?\+s*sha256.*:\s+"[a-f0-9]{64}"'
          AWK_SCRIPT: |
            /^\+\+<<<<<<< / {inconflict=1; next}
            /^\+\+=======/ {next}
            /^\+\+>>>>>>> / {inconflict=0; next}
            inconflict
        run: |
          git config --global user.email "github@carlo.cab"
          git config --global user.name "Carlo Cabrera"
          git checkout -b old-main 4f8215e39463753cc71d78650f021112eb776ff2
          git checkout -b feature f3ecdbd01a5bdf94430d4f974b27525f8e56045e
          if ! git merge --no-commit --no-ff old-main
          then
            set +o pipefail
            git diff | awk "${AWK_SCRIPT}"
          fi
