name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Install GCC 12
        run: brew install gcc@12
      - name: Build OpenBLAS
        run: |
          OPENBLAS_VERSION=0.3.20
          TARBALL="https://github.com/xianyi/OpenBLAS/releases/download/v${OPENBLAS_VERSION}/OpenBLAS-${OPENBLAS_VERSION}.tar.gz"

          curl -L "$TARBALL" | tar -x
          cd "OpenBLAS-${OPENBLAS_VERSION}"

          export DYNAMIC_ARCH=1
          export USE_OPENMP=1
          export NUM_THREAD=56

          if [[ "$(uname -s)" = Darwin ]]
          then
            export TARGET=NEHALEM
          else
            export TARGET=CORE2
          fi

          make CC=gcc-12 FC=gfortran-12 libs netlib shared
          make PREFIX=/usr/local install

      - name: Test installation
        run: |
          cat <<EOS | gcc-12 -I/usr/local/include -L/usr/local/lib -lopenblas -o test
            #include <stdio.h>
            #include <stdlib.h>
            #include <math.h>
            #include "cblas.h"

            int main(void) {
              int i;
              double A[6] = {1.0, 2.0, 1.0, -3.0, 4.0, -1.0};
              double B[6] = {1.0, 2.0, 1.0, -3.0, 4.0, -1.0};
              double C[9] = {.5, .5, .5, .5, .5, .5, .5, .5, .5};
              cblas_dgemm(CblasColMajor, CblasNoTrans, CblasTrans,
                          3, 3, 2, 1, A, 3, B, 3, 2, C, 3);
              for (i = 0; i < 9; i++)
                printf("%lf ", C[i]);
              printf("\n");
              if (fabs(C[0]-11) > 1.e-5) abort();
              if (fabs(C[4]-21) > 1.e-5) abort();
              return 0;
            }
          EOS

          ./test
