name: CI
on: push

jobs:
  test:
    runs-on: macos-${{ matrix.macos-version }}
    strategy:
      fail-fast: false
      matrix:
        macos-version: [13, 14, 15]
        overwrite: [true, false]

    steps:
      - run: brew update
      - run: brew deps llvm | xargs brew fetch --concurrency=64 llvm
      - run: brew install ${FLAG} llvm
        env:
          FLAG: ${{ matrix.overwrite && '--overwrite' || '' }}
