name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        formula: [nuvie, pce, pmdmini, qdae, supermodel, sz81, vecx, xrick]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Build ${{ matrix.formula }}
        env:
          FORMULA: ${{ matrix.formula }}
        run: |
          brew fetch --retry --build-bottle --force "$FORMULA"
          brew install --only-dependencies --build-bottle "$FORMULA"
          brew install --verbose --build-bottle "$FORMULA"
