name: CI
on: push

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    name: Run `brew tests --only=os/mac/pkgconfig`
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - run: brew tests --only=os/mac/pkgconfig
