name: CI
on: pull_request

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  GH_API_HEADER_FLAGS: '["--header", "Accept:application/vnd.github+json", "--header", "X-GitHub-Api-Version:2022-11-28"]'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  outside_container:
    runs-on: ubuntu-latest
    steps:
      - name: Show `GITHUB_ variables`.
        run: |
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(env | grep -E '^GITHUB_' | sort)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

  inside_container:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

        run: |
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(env | grep -E '^GITHUB_' | sort)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
