name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: 'Checkout #13918'
        run: |
          pushd "$(brew --repository)"
          git fetch origin pull/13918/head:fix_gcc_dependency
          git checkout fix_gcc_dependency
          popd

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Audit for Linux-only GCC dependencies.
        run: |
          brew audit --strict --only=gcc_dependency --tap=homebrew/core
