name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
      fail-fast: false
    steps:
      - name: What is $GITHUB_STEP_SUMMARY?
        run: |
          echo "$GITHUB_STEP_SUMMARY"
          file "$GITHUB_STEP_SUMMARY"
      - name: Find compilers
        run: |
          echo "# Clang version" >> $GITHUB_STEP_SUMMARY
          printf '```\n%s\n```\n' "$(clang --version)" >> $GITHUB_STEP_SUMMARY
          printf '```\n%s\n```\n' "$(clang -dumpversion)" >> $GITHUB_STEP_SUMMARY
          echo "# GCC version" >> $GITHUB_STEP_SUMMARY
          printf '```\n%s\n```\n' "$(gcc --version)" >> $GITHUB_STEP_SUMMARY
          printf '```\n%s\n```\n' "$(gcc -dumpversion)" >> $GITHUB_STEP_SUMMARY

          echo "# Alternative Versions" >> $GITHUB_STEP_SUMMARY

          for v in 12 13 14
          do
            printf '```\n%s\n```\n' "$(clang-${v} --version)" >> $GITHUB_STEP_SUMMARY
            printf '```\n%s\n```\n' "$(clang-${v} -dumpversion)" >> $GITHUB_STEP_SUMMARY
          done

          for v in 9 10 11
          do
            printf '```\n%s\n```\n' "$(gcc-${v} --version)" >> $GITHUB_STEP_SUMMARY
            printf '```\n%s\n```\n' "$(gcc-${v} -dumpversion)" >> $GITHUB_STEP_SUMMARY
          done
