name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test timescaledb install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Show signals sent at timeout
        run: |
          brew update
          brew tap timescaledb/tap
          brew install timescaledb
