name: CI
on: [push, pull_request]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false
    timeout-minutes: ${{ (matrix.os == 'ubuntu-latest' && 3) || 1 }}
    steps:
      - run: sleep 120
