name: CI
on: push

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-13, macos-14, macos-15]
    env:
      HOMEBREW_DOWNLOAD_CONCURRENCY: auto
      HOMEBREW_DEVELOPER: 1
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - run: brew config

      - run: brew doctor
        continue-on-error: ${{ runner.os == 'macOS' }}

      - run: brew list --cask
