name: CI
on: push

jobs:
  test:
    runs-on: macos-${{ matrix.macos-version }}
    strategy:
      fail-fast: false
      matrix:
        macos-version: [13, 14, 15]
        install-clt: [true, false]
        exclude:
          - macos-version: 13
            install-clt: true
          - macos-version: 14
            install-clt: true
    steps:
      - name: Find newest installed LLVM
        shell: brew ruby {0}
        run: |
          installed_llvm_formulae = Formula.installed.select { |formula| formula.name.match?(/^llvm(@\d+)?$/) }
          newest_llvm = installed_llvm_formulae.max_by(&:version)
          github_env = ENV.fetch("GITHUB_ENV")
          File.open(github_env, "a") do |f|
            f.puts("LLVM_PREFIX=#{newest_llvm.opt_prefix}")
          end

      - name: Print LLVM version info
        run: |
          "${LLVM_PREFIX}/bin/clang" --version

      - name: Write test C file
        run: |
          cat <<'SOURCE' > test.c
            #include <stdio.h>
            int main() {
              printf("hello, world!\n");
            }
          SOURCE

      - name: Check CLT installation
        continue-on-error: true
        run: |
          stat /Library/Developer/CommandLineTools
          ls -la /Library/Developer/CommandLineTools

      - name: Install CLT
        if: matrix.install-clt
        run: |
          # Taken from Homebrew install script
          clt_placeholder="/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
          sudo touch clt_placeholder

          clt_label="$(
            /usr/sbin/softwareupdate -l |
            grep -B 1 -E 'Command Line Tools' |
            awk -F'*' '/^ *\\*/ {print \$2}' |
            sed -e 's/^ *Label: //' -e 's/^ *//' |
            sort -V |
            tail -n1
          )"
          clt_label="$(printf "%s" "${clt_label/"$'\n'"/}")"

          sudo /usr/sbin/softwareupdate -i "${clt_label}"
          sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools


      - name: Compile `test.c`
        run: |
          "${LLVM_PREFIX}/bin/clang" -v test.c -o test

      - name: Run `test`
        run: ./test

