name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1
  FORMULA: python@3.10

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Show `python@3.10` dependents.
        run: |
          recursive_non_build_dependents="$(brew uses --eval-all --include-test --recursive --formula $FORMULA)"
          build_dependents="$(brew uses --eval-all --include-build --formula $FORMULA)"
          ALL_DEPENDENTS="$(cat <<<$recursive_non_build_dependents <<<$build_dependents | sort -u)"
          printf 'ALL_DEPENDENTS=%s\n' "$ALL_DEPENDENTS" >> "$GITHUB_ENV"
          printf '### `python@3.10` dependents\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$ALL_DEPENDENTS" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Count `python@3.10` dependents.
        run: |
          printf '### `python@3.10` dependents count\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(wc -l <<<$ALL_DEPENDENTS)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
