name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update -y
          sudo apt-get install -y systemd

      - run: uname -a

      - run: which -a journalctl

      - run: journalctl

      - run: echo '${{ defaults.run.shell }}'
