name: CI
on: [push, workflow_dispatch]

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test outputs
        id: test
        run: |
          printf 'output=hello\n' >> "$GITHUB_OUTPUT"
          printf 'output was ${{outputs.output}}\n' | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Another step
        run: printf 'output from previous step was: ${{steps.test.outputs.output}}\n' | tee -a "$GITHUB_STEP_SUMMARY"
