name: CI
on: push

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    name: ${{ format('{0}-{1}', matrix.runner, startsWith(matrix.commit, '04b') && 'Broken' || (matrix.commit == 'patchelf-test' && 'Patchelf' || 'Fixed')) }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest
        commit:
          - 04b47bc1aa7a765d51012d230634a248377d076c
          - c9060c3242c465d1a8f557147c1feb068a0b35f3
          - patchelf-test
    container:
      image: ${{ matrix.runner == 'ubuntu-latest' && 'ghcr.io/homebrew/ubuntu22.04:main' || '' }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          test-bot: true

      - run: brew update

      - name: Remove installed formulae and taps
        run: |
          brew list | xargs brew uninstall --force --ignore-dependencies
          brew tap | grep -v 'homebrew/test-bot' | xargs brew untap --force
        if: runner.os == 'macOS'

      - name: Check out commit to test
        run: |
          cd "$(brew --repository)"
          git fetch origin "${COMMIT}"
          git checkout FETCH_HEAD
          echo "HOMEBREW_NO_AUTO_UPDATE=1" >>"${GITHUB_ENV}"
        env:
          COMMIT: ${{ matrix.commit }}

      - run: brew install protobuf

      - run: brew linkage protobuf

      - run: brew linkage --test protobuf
        if: always()

      - run: brew test-bot --only-formulae or-tools
        if: always()
