name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - run: |
          ls -la /Library/Frameworks
          ls -la /Library/Frameworks/Mono.framework
          ls -la /Library/Frameworks/Mono.framework/Headers
          cat /Library/Frameworks/Mono.framework/Headers/libintl.h
