name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bool: [true, false]
      fail-fast: false
    steps:
      - name: Execute `${{ matrix.bool }}`
        run: |
          false

      - name: See what happens next
        if: ${{ matrix.bool && always() }}
        run: echo "executed!"
