name: CI
on: push

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:main
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          test-bot: true

      - run: brew update

      - name: Ensure that failure is reproducible
        run: brew test-bot --only-formulae or-tools
        continue-on-error: true

      - name: Clean stray bottle files
        run: rm -fv **/*.bottle*

      - name: Check out `protodesc_cold` PR fix
        run: |
          cd "$(brew --repository)"
          gh pr checkout 20403
          echo "HOMEBREW_NO_AUTO_UPDATE=1" >>"${GITHUB_ENV}"
        env:
          GH_TOKEN: ${{ github.token }}

      - run: brew uninstall --force or-tools

      - run: brew test-bot --only-formulae or-tools
