name: CI
on: push

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    name: Build OpenVINO on arm64 Linux
    runs-on: ubuntu-22.04-arm
    container:
      image: ghcr.io/homebrew/ubuntu22.04:main
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true
          test-bot: true

      - run: brew update

      - name: Check out PR fix
        run: |
          cd "$(brew --repository homebrew/core)"
          git fetch origin openvino-aarch64-linux
          git checkout openvino-aarch64-linux

      - run: brew test-bot --only-formulae --keep-old --only-json-tab --skip-online-checks --skip-dependents openvino
