name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test patchelf
    runs-on: ubuntu-latest
    steps:
      - name: Run `brew update`
        run: brew update

      - name: Check brew version
        run: brew --version

      - name: Show `brew config`
        run: brew config

      - name: Run `brew doctor`
        run: brew doctor || true

      - name: Install patchelf
        run: brew install patchelf

      - name: Dump patchelf RPATH
        run: |
          cd "$(brew --prefix patchelf)/bin"
          readelf -d patchelf
