name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Show installed formulae
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
      fail-fast: false
    steps:
      - name: Run `brew list --formula`
        run: brew list --formula --full-name

      - name: Run `brew list --cask`
        run: brew list --cask --full-name
