name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    env:
      FORMULA: ${{ matrix.formula }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        formula: [hello, llvm, gcc, python@3.10, sqlite, icu4c, node, glib, readline, harfbuzz, icu4c]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Check out GCC PR
        run: |
          pushd "$(brew --repository homebrew/core)"
          git fetch origin pull/111830/head:gcc-specs-fix
          git checkout gcc-specs-fix
          popd

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: List installed formulae
        run: |
          printf '### `brew list --formula` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew list --formula)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Install formula
        run: |
          if brew install "$FORMULA"
          then
            printf "**%s install successful!** :tada:\n" "$FORMULA" >> "$GITHUB_STEP_SUMMARY"
          else
            printf "**%s install failed** :cry:\n" "$FORMULA" >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

      - name: Postinstall GCC if needed
        if: runner.os == 'Linux' && matrix.os != 'ubuntu-22.04'
        run: brew postinstall gcc

      - name: Install test dependencies
        run: brew install --only-dependencies --include-test "$FORMULA"

      - name: Test formula
        run: |
          if brew test --verbose "$FORMULA"
          then
            printf "**%s test successful!** :tada:\n" "$FORMULA" >> "$GITHUB_STEP_SUMMARY"
          else
            printf "**%s test failed** :cry:\n" "$FORMULA" >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi
