name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
      fail-fast: false
    steps:
      - name: Show `xcode-select -p`
        run: xcode-select -p

      - name: Check `-no_fixup_chains` flag
        run: |
          cat <<EOS > test.c
            int main(){}
          EOS
          clang -Wl,-v -Wl,-no_fixup_chains test.c
