name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Print some GitHub variables
        run: |
          echo ${{ github.graphql_url }}
          echo ${{ github.api_url }}
          echo ${{ github.repository }}
