name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ true && 'hi' || '' }}
          echo ${{ false && 'hi' || '' }}
