name: CI
on: push

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<BASH > test.sh
          #!/usr/bin/env bash
          echo "$#"
          BASH
          chmod +x test.sh

          ./test.sh ${{ false && 'foo' || 'bar baz' }}
