name: CI
on: [push, workflow_dispatch]

env:
  MESSAGE: >
    This is a long message, that may contain a
    [URL](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

jobs:
  tests:
    name: Test
    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        do_deps: [true, false]
      fail-fast: false
    outputs:
      runner: ${{steps.runner.outputs.runner}}
      dodeps: ${{steps.runner.outputs.dodeps}}
    steps:
      - name: Test outputs
        id: test
        run: |
          printf 'output=hello\n' >> "$GITHUB_OUTPUT"
          printf 'output was ${{steps.test.outputs.output}}\n' | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Another step
        run: |
          printf 'output from previous step was: ${{steps.test.outputs.output}}\n' | tee -a "$GITHUB_STEP_SUMMARY"
          printf "This is a message: %s\n" "$MESSAGE" | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Determine dependent runner
        id: runner
        run: |
          if ${{matrix.do_deps}}
          then
            sleep 15
            echo "runner=ubuntu-latest" >> "$GITHUB_OUTPUT"
            echo "dodeps=true" >> "$GITHUB_OUTPUT"
          else
            exit 1
          fi

  dependent_tests:
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: sleep 1
      - run: |
          printf 'conclusion was ${{needs.tests.result}}\n' | tee -a "$GITHUB_STEP_SUMMARY"
