name: CI
on: push

jobs:
  test:
    strategy:
      matrix:
        runner: ['ubuntu-latest', 'ubuntu-22.04-arm']
    runs-on: ${{ matrix.runner }}
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
      options: --user=linuxbrew
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew install gcc

      - run: /home/linuxbrew/.linuxbrew/opt/gcc/libexec/gcc/aarch64-unknown-linux-gnu/14/install-tools/fixincl -h
