name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12]
        formula: [llvm]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Show formula info.
        env:
          FORMULA: ${{ matrix.formula }}
        run: |
          output="$(brew info --formula "$FORMULA")"
          status="$?"
          printf '### `brew info %s` output\n' "$FORMULA" >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$output" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          exit "$status"

      - name: Install formula.
        env:
          FORMULA: ${{ matrix.formula }}
        run: brew install "$FORMULA"

      - name: Show formula linkage.
        env:
          FORMULA: ${{ matrix.formula }}
        run: |
          output="$(brew linkage "$FORMULA")"
          status="$?"
          printf '### `brew linkage %s` output\n' "$FORMULA" >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$output" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          exit "$status"

      - name: Install formula dependencies.
        env:
          FORMULA: ${{ matrix.formula }}
        run: |
          brew link --overwrite python@3.11
          brew install --only-dependencies --include-test "$FORMULA"

      - name: Test formula.
        env:
          FORMULA: ${{ matrix.formula }}
        run: brew test --verbose "$FORMULA"

      - name: Remove CLT
        run: sudo rm -rf /Library/Developer/CommandLineTools

      - name: Try compiling with LLVM Clang
        run: |
          echo "int main(){}" > test.c
          /usr/local/opt/llvm/bin/clang test.c
          ./a.out
