name: CI
on: [push, pull_request]

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  outside_container:
    runs-on: ubuntu-latest
    steps:
      - name: Show `GITHUB_ variables`.
        run: |
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(env | sort)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Dump GitHub event payload
        run: |
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(jq . "$GITHUB_EVENT_PATH")" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

  inside_container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - run: |
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(env | sort)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Dump GitHub event payload
        run: |
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(jq . "$GITHUB_EVENT_PATH")" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
