name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test timescaledb install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
      fail-fast: false
    steps:
      - name: Run `brew update`
        run: brew update

      - name: Install timescaledb
        run: |
          brew tap timescaledb/tap
          brew install timescaledb
