name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Show Xcode SDK
        run: |
          brew ruby <<RUBY
            sdk = MacOS::Xcode.sdk
            puts sdk.path
            puts sdk.version
          RUBY

      - name: Show CLT SDK
        run: |
          brew ruby <<RUBY
            sdk = MacOS::CLT.sdk
            puts sdk.path
            puts sdk.version
          RUBY
