name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false
    steps:
      - run: brew ls --formula
      - run: |
          brew install carlocab/personal/libwhich
          if [[ "$(uname -s)" = "Darwin" ]]
          then
            LIBEXT="dylib"
          else
            LIBEXT="so"
          fi
          libwhich "libintl.$LIBEXT"
