name: CI
on: [push, pull_request]

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    name: Check `GITHUB_BASE_REF`
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_BASE_REF}"
      - run: echo "${GITHUB_HEAD_REF}"
