name: CI
on: [push, pull_request]

env:
  HOMEBREW_NO_INSTALL_FROM_API: 1

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [macos-latest, ubuntu-latest]
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true

      - run: brew install --build-from-source glib

      - run: python3 -c "from gi.repository import GLib"
