name: CI
on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: brew install go

      - uses: actions/setup-go@v5

      - run: |
          printf '```\n' >> "${GITHUB_STEP_SUMMARY}"
          {
            which -a go
            go env
          } | tee -a "${GITHUB_STEP_SUMMARY}"
          printf '```\n' >> "${GITHUB_STEP_SUMMARY}"
