name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      merge_strategy:
        type: choice
        description: "merge strategy"
        options:
          - merge
          - rebase
          - squash
        default: rebase
        required: false

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-latest
    steps:
      - name: Show chosen merge strategy
        run: echo 'You chose strategy ${{github.event.inputs.merge_strategy}}'
