name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Install `glibc`.
        run: brew install glibc

      - name: Install `gcc@11` dependencies.
        run: brew install --only-dependencies gcc@11

      - name: Install `gcc@11`.
        run: brew install gcc@11

      - name: Install `python@3.9`.
        run: brew install python@3.9

      - name: Unlink `glibc`.
        run: brew unlink glibc

      - name: Run `python3.9 --version`.
        run: |
          "$(brew --prefix python@3.9)/bin/python3.9" --version

      - name: Run `brew test python@3.9`.
        run: |
          printf '### `brew test python@3.9` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew test --verbose python@3.9)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
