name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Install `libarchive`
        run: brew install libarchive

      - name: Create `.tar.zst` archive
        run: |
          mkdir -p foo
          touch foo/{bar,baz,qux}
          /usr/local/opt/libarchive/bin/tar -czvf foo.tar.zst ./foo
          rm -rf foo

      - name: Uninstall `libarchive` and dependencies
        run: brew uninstall $(brew deps libarchive) libarchive

      - name: Untar `foo.tar.zst`
        run: |
          tar -xvf foo.tar.zst
          file foo
          ls -la foo
