name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    env:
      FORMULA: ${{ matrix.formula }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        formula: [hello, llvm, gcc, python@3.10, sqlite, icu4c, node, glib, readline harfbuzz icu4c]
      fail-fast: false
    steps:
      - name: Make sure `brew` is in PATH
        if: runner.os == 'Linux'
        run: |
          eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
          printf 'PATH=%s\n' "$PATH" >> "$GITHUB_ENV"

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Check out GCC PR
        run: |
          pushd "$(brew --repository)"
          git fetch origin pull/13916/head:unversioned-gcc-runtime
          git checkout unversioned-gcc-runtime
          git rebase origin/master
          popd

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Install formula
        run: brew install "$FORMULA"

      - name: Test formula
        run: brew test --verbose "$FORMULA"
