name: CI
on: push

jobs:
  debug:
    strategy:
      matrix:
        runner: [macos-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - run: |
          cat <<BASH > test.sh
          #!/bin/bash
          echo $1
          echo $@
          echo $#
          BASH
          chmod +x test.sh

      - run: ./test.sh ${{ false && 'foo' || 'bar baz' }}
      - run:  /bin/bash test.sh ${{ false && 'foo' || 'bar baz' }}
