name: CI
on: [push, pull_request]

env:
  HOMEBREW_NO_INSTALL_FROM_API: 1

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true

      - run: echo "HOMEBREW_NO_INSTALL_FROM_API=1" >>"${GITHUB_ENV}"

      - run: brew uninstall --force --ignore-dependencies glib

      - run: |
          cd "$(brew --repository homebrew/core)"
          git checkout e3562695f2369d96d7a5568f50dba3504715e22e -- Formula/m/meson.rb

      - run: brew install --build-from-source glib

      - run: brew install pygobject3

      - run: /opt/homebrew/bin/python3 -c "from gi.repository import GLib"
