name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }} with gcc-${{ matrix.gcc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Install GFortran
        run: |
          sudo apt update
          sudo apt install -y gfortran

      - name: Install Homebrew `binutils`
        run: brew install binutils

      - name: Ensure `brew` is first in `PATH`
        run: |
          PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"
          tr ':' '\n' <<<"$PATH"
          printf 'PATH=%s\n' "$PATH" >> "$GITHUB_ENV"

      - name: Build OpenBLAS
        run: |
          OPENBLAS_VERSION=0.3.20
          DIRECTORY_NAME="OpenBLAS-${OPENBLAS_VERSION}"
          TARBALL_NAME="${DIRECTORY_NAME}.tar.gz"
          TARBALL_URL="https://github.com/xianyi/OpenBLAS/releases/download/v${OPENBLAS_VERSION}/${TARBALL_NAME}"

          curl -OL "$TARBALL_URL"
          tar -xf "$TARBALL_NAME"
          cd "$DIRECTORY_NAME"

          make CC=gcc FC=gfortran libs netlib shared
          sudo make PREFIX=/usr/local install

      - name: Show contents of `/usr/local/lib`
        run: ls -la /usr/local/lib

      - name: Test installation
        run: |
          cat <<EOS > test.c
            #include <stdio.h>
            #include <stdlib.h>
            #include <math.h>
            #include "cblas.h"

            int main(void) {
              int i;
              double A[6] = {1.0, 2.0, 1.0, -3.0, 4.0, -1.0};
              double B[6] = {1.0, 2.0, 1.0, -3.0, 4.0, -1.0};
              double C[9] = {.5, .5, .5, .5, .5, .5, .5, .5, .5};
              cblas_dgemm(CblasColMajor, CblasNoTrans, CblasTrans,
                          3, 3, 2, 1, A, 3, B, 3, 2, C, 3);
              for (i = 0; i < 9; i++)
                printf("%lf ", C[i]);
              printf("\n");
              if (fabs(C[0]-11) > 1.e-5) abort();
              if (fabs(C[4]-21) > 1.e-5) abort();
              return 0;
            }
          EOS

          gcc -I/usr/local/include test.c -L/usr/local/lib -lopenblas -o test
          LD_LIBRARY_PATH=/usr/local/lib ./test
