name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Benchmark `brew doctor`
    runs-on: ubuntu-latest
    steps:
      - name: Run `brew update`
        run: brew update

      - name: Install patchelf
        run: brew install patchelf

      - name: Dump patchelf RPATH
        run: |
          cd "$(brew --prefix patchelf)/bin"
          readelf -d patchelf
