name: CI
on: push

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - id: fake
        run: false

      - if: fromJson(steps.fake.outputs.nonexistent) || !success()
        run: echo "it worked"
