name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1
  FORMULA: openjdk

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Audit formula for Linux-only GCC dependency.
        run: brew audit --strict --only=gcc_dependency "$FORMULA"

      - name: Audit for Linux-only GCC dependencies.
        run: |
          brew audit --strict --only=gcc_dependency --tap=homebrew/core
