name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Install Homebrew LLVM
        run: brew install llvm
      - name: Try to link with `libcrypto`
        run: |
          $(brew --prefix llvm)/bin/clang -v -xc - --sysroot='' -Wl,-v,-L/usr/lib,-lcrypto <<'EOS'
            int main() {}
          EOS
          command -v otool > /dev/null && otool -L ./a.out
          ./a.out
