name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  record_pull_number:
    runs-on: ubuntu-latest
    steps:
      - name: Save pull request number
        if: github.event_name == 'pull_request'
        env:
          PR: ${{github.event.number}}
        run: |
          mkdir -p pr
          echo "$PR" > pr/number

      - uses: actions/upload-artifact@v3
        if: github.event_name == 'pull_request'
        with:
          name: pull-number
          path: pr

      - name: Check CI labels
        uses: actions/github-script@v6
        with:
          script: |
            const labelCountQuery = `query paginate($cursor:String, $owner:String!, $name:String!, $label:String!) {
              repository(owner:$owner, name:$name) {
                pullRequests(last: 100, states: OPEN, labels: [$label], after: $cursor) {
                  totalCount
                  pageInfo {
                    hasPreviousPage
                    endCursor
                  }
                }
              }
            };`

            const response = await github.graphql.paginate(
              labelCountQuery, {
                owner: 'Homebrew',
                name: 'homebrew-core',
                label: 'bump-formula-pr'
              }
            );

            const count = response.repository.pullRequests.totalCount
            console.log(`Found ${count} PRs!`);


  tests:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    steps:
      - name: Show `gh version`.
        run: |
          printf '### `gh version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(gh version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Show `gh pr merge --help`.
        run: |
          printf '### `gh pr merge --help` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(gh pr merge --help)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
