name: CI
on: push

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:main
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          test-bot: true

      - run: brew update

      - run: |
          cd "$(brew --repository)"
          gh pr checkout 20403
          echo "HOMEBREW_NO_AUTO_UPDATE=1" >>"${GITHUB_ENV}"

      - run: brew install --build-from-source or-tools

      - run: brew test --verbose or-tools

      - run: brew uninstall --force or-tools

      - run: brew test-bot --only-formulae or-tools
