name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Poke at /usr/lib
        run: ls -la /usr/lib
      - name: Try to link with `libcrypto`
        run: |
          clang -xc - -L/usr/lib -lcrypto -Wl,-v <<'EOS'
            int main() {}
          EOS
          command -v otool > /dev/null && otool -L ./a.out
          ./a.out
