name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - run: |
          echo "=========== /Library/Frameworks =========="
          ls -la /Library/Frameworks
          echo "=========== /Library/Frameworks/Mono.framework =========="
          ls -la /Library/Frameworks/Mono.framework
          echo "=========== /Library/Frameworks/Mono.framework/Headers =========="
          ls -la /Library/Frameworks/Mono.framework/Headers
          ls -la "$(readlink /Library/Frameworks/Mono.framework/Headers)"
          echo "=========== /Library/Frameworks/Mono.framework/Headers/libintl.h =========="
          cat /Library/Frameworks/Mono.framework/Headers/libintl.h
