name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1
  FORMULA: llvm

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: List installed formulae
        run: |
          printf '### `brew list --formula` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew list --formula)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Set logs directory
        run: printf 'HOMEBREW_LOGS=%s\n' "$(pwd)/Logs" >> "$GITHUB_ENV"

      - name: Install formula
        run: |
          if brew install "$FORMULA"
          then
            printf ":white_check_mark: **%s install successful!** :white_check_mark:\n" "$FORMULA" >> "$GITHUB_STEP_SUMMARY"
          else
            printf ":x: **%s install failed** :x:\n" "$FORMULA" >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

      - name: Write `clang` config files
        run: |
          llvm_prefix="$(brew --prefix llvm)"
          gcc_prefix="$(brew --prefix gcc)"
          glibc_prefix="$(brew --prefix glibc)"
          target_triple="$(clang -print-target-triple)"

          cat <<EOS > "$llvm_prefix/bin/clang.cfg"
          --gcc-toolchain=$gcc_prefix
          -Wl,-dynamic-linker="$(brew --prefix)/lib/ld.so"
          -B${glibc_prefix}/lib
          -L${glibc_prefix}/lib
          EOS

          cat <<EOS > "$llvm_prefix/bin/clang++.cfg"
          --gcc-toolchain=$gcc_prefix
          -Wl,-dynamic-linker="$(brew --prefix)/lib/ld.so"
          -B${glibc_prefix}/lib
          -L${glibc_prefix}/lib
          EOS

      - name: Pass `--gcc-toolchain` to clang
        run: |
          sed -i -E -e 's/(clang(\+\+)?",)/\1 "--gcc-toolchain=#{Formula["gcc"].opt_prefix}",/' "$(brew --repository homebrew/core)/Formula/llvm.rb"

      - name: Install test dependencies
        run: brew install --only-dependencies --include-test "$FORMULA"

      - name: Test formula
        run: |
          if brew test --verbose "$FORMULA"
          then
            printf ":white_check_mark: **%s test successful!** :white_check_mark:\n" "$FORMULA" >> "$GITHUB_STEP_SUMMARY"
          else
            printf ":x: **%s test failed** :x:\n" "$FORMULA" >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: Logs
