name: CI
on: push

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04-arm
    container:
      image: ghcr.io/homebrew/ubuntu22.04:main
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true
          cask: false
          test-bot: false

      - run: brew config

      - name: set `HOMEBREW_MAKE_JOBS`
        run: echo "HOMEBREW_MAKE_JOBS=1" >>"${GITHUB_ENV}"

      - run: brew config

      - run: brew install --build-bottle qt
