name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
      fail-fast: false
    steps:
      - name: Check `six` module
        run: /usr/bin/python -c 'import six'
