name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
      fail-fast: false
    steps:
      - name: Run `brew update`
        run: brew update

      - name: Install tectonic
        run: brew install tectonic

      - name: Show tectonic linkage
        run: brew linkage tectonic
