name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Uninstall everything.
        run: brew uninstall $(brew list)

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Install `gcc@11`.
        run: brew install gcc@11

      - name: Check `gcc@11`'s rack.
        run: ls -la $(brew --cellar gcc@11)

      - name: Test `gcc@11` linkage.
        run: |
          printf '## `brew linkage --test gcc@11` on ${{ matrix.os }} :test_tube:\n' >> "$GITHUB_STEP_SUMMARY"
          if brew linkage --test gcc@11
          then
            printf 'success! :tada:\n' >> "$GITHUB_STEP_SUMMARY"
          else
            printf 'failed :cry:\n' >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi
