name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  GH_API_HEADER_FLAGS: '["--header", "Accept:application/vnd.github+json", "--header", "X-GitHub-Api-Version:2022-11-28"]'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  api_query_test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
            ${{ join(fromJson(env.GH_API_HEADER_FLAGS), ' ') }} \
            repos/Homebrew/homebrew-core/pulls/129512

  record_pull_number:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Show `GITHUB_ variables`.
        run: |
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(env | grep -E '^GITHUB_')" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Save pull request number
        env:
          PR: ${{github.event.number}}
        run: |
          mkdir -p pr
          echo "$PR" > pr/number

      - uses: actions/upload-artifact@v3
        with:
          name: pull-number
          path: pr

  outputs_test:
    runs-on: ubuntu-latest
    steps:
      - id: many-outputs
        run: |
          echo "out=foo" >> "$GITHUB_OUTPUT"
          echo "out=bar" >> "$GITHUB_OUTPUT"
          echo "out=baz" >> "$GITHUB_OUTPUT"

      - run: echo '${{ steps.many-outputs.outputs.out }}'

  more_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Show environment variables
        run: |
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf 'HOME=%s\n' "$HOME" | tee -a "$GITHUB_STEP_SUMMARY"
          printf 'GITHUB_WORKSPACE=%s\n' "$GITHUB_WORKSPACE" | tee -a "$GITHUB_STEP_SUMMARY"
          printf 'pwd=%s\n' "$(pwd)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

  tests:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

        run: |
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(env | grep -E '^GITHUB_')" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
