name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Install `mold`
        run: brew install mold
      - name: Try to link with `libcrypto`
        run: |
          clang -fuse-ld=mold -xc - -L/usr/lib -lssl -Wl,-v <<'EOS'
            int main() {}
          EOS
          command -v otool > /dev/null && otool -L ./a.out
          ./a.out
