name: CI
on: push

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          FOO="foo
          bar
          baz"

          echo "$FOO"
          FOO="${FOO//'%'/'%25'}"
          FOO="${FOO//$'\n'/'%0A'}"
          FOO="${FOO//$'\r'/'%0D'}"
          echo "$FOO"

          echo "::notice ::$FOO"

