name: CI
on: [push, pull_request]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    timeout-minutes: ${{ (matrix.os == 'ubuntu-latest' && '2') || '1' }}
    steps:
      - run: sleep 90
