name: CI
on: push

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.concurrency && format('{0}-concurrent', matrix.runner) || matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest]
        concurrency: [true, false]
    env:
      HOMEBREW_DOWNLOAD_CONCURRENCY: ${{ matrix.concurrency && '1' || '' }}
    container:
      image: ${{ matrix.runner == 'ubuntu-latest' && 'ghcr.io/homebrew/ubuntu22.04:main' || '' }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true

      - name: Set environment variables
        run: |
          echo "HOMEBREW_NO_INSTALL_FROM_API=1" >>"${GITHUB_ENV}"
          echo "HOMEBREW_DEVELOPER=1" >>"${GITHUB_ENV}"
          echo "HOMEBREW_AUTO_UPDATE_SECS=43200"

      - run: brew config

      - run: brew doctor
        continue-on-error: ${{ runner.os == 'macOS' }}

      - run: brew ruby -e 'puts "hello"'

      - run: brew update

      - run: rm -rfv "$(brew --cache)"/api*

      - run: brew info hello

      - run: rm -rfv "$(brew --cache)"/api*

      - run: brew install hello

      - run: rm -rfv "$(brew --cache)"/api*

      - run: brew uninstall hello
