name: CI
on: push

jobs:
  test:
    strategy:
      matrix:
        version: [12, 13, 14, 15]
    runs-on: macos-${{ matrix.version }}
    steps:
      - run: |
          printf '### `uname -r` output on macOS %d\n' "${VERSION}" >>"${GITHUB_STEP_SUMMARY}"
          printf '```\n' >>"${GITHUB_STEP_SUMMARY}"
          uname -r | tee -a "${GITHUB_STEP_SUMMARY}"
          printf '```\n' >>"${GITHUB_STEP_SUMMARY}"
        env:
          VERSION: ${{ matrix.version }}

