name: CI
on: [push, workflow_dispatch]

env:
  MESSAGE: >
    This is a long message, that may contain a
    [URL](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      runner: ${{steps.runner.outputs.runner}}
      dodeps: ${{steps.runner.outputs.dodeps}}
    steps:
      - name: Test outputs
        id: test
        run: |
          printf 'output=hello\n' >> "$GITHUB_OUTPUT"
          printf 'HOME=%s\n' "$HOME" | tee -a "$GITHUB_STEP_SUMMARY"
          original_uid="$(stat --printf='%u' "$GITHUB_WORKSPACE")"
          ls_uid="$(ls -nd "$GITHUB_WORKSPACE" | awk 'NR==1 {print $3}')"
          printf 'original_uid=%d\n' "$original_uid" | tee -a "$GITHUB_STEP_SUMMARY"
          printf 'ls_uid=%d\n' "$ls_uid" | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Another step
        run: |
          printf 'output from previous step was: ${{steps.test.outputs.output}}\n' | tee -a "$GITHUB_STEP_SUMMARY"
          printf "This is a message: %s\n" "$MESSAGE" | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Determine dependent runner
        id: runner
        run: |
          echo "runner=ubuntu-latest" >> "$GITHUB_OUTPUT"
          echo "dodeps=true" >> "$GITHUB_OUTPUT"
          false
          true

  dependent_tests:
    needs: tests
    if: always() && (!false)
    runs-on: ubuntu-latest
    steps:
      - run: sleep 1
      - run: |
          printf 'conclusion was ${{needs.tests.result}}\n' | tee -a "$GITHUB_STEP_SUMMARY"
