name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1
  FORMULA: qt

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-18.04, ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Set up Homebrew.
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout `master`.
        run: git -C "$(brew --repository)" checkout master

      - name: Uninstall everything
        run: brew uninstall $(brew list)

      - name: Install formula.
        run: brew install "$FORMULA"

      - name: Show `brew --version`.
        run: |
          printf '### Homebrew version\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          brew --version | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Show formula linkage
        run: |
          printf '### `%s` linkage\n' "$FORMULA" >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          brew linkage "$FORMULA" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
