name: CI

on: push

env:
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_DEVELOPER: 1

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
      options: --user=linuxbrew
    timeout-minutes: 360
    env:
      HOMEBREW_LOGS: ${{ github.workspace }}/logs-before
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - run: |
          cd "$(brew --repository homebrew/core)"
          gh pr checkout 134428
        env:
          GH_TOKEN: ${{ github.token }}

      - run: brew install --build-bottle apache-arrow

      - run: file "$(brew --prefix apache-arrow)/lib/libarrow_acero.so"*

      - run: cp "$(brew --prefix apache-arrow)/lib/libarrow_acero.so"* logs-before/

      - run: brew install --build-from-source --verbose gdal

      - run: echo 'HOMEBREW_LOGS=${{ github.workspace }}/logs-after' >> "${GITHUB_ENV}"

      - run: brew uninstall gdal

      - run: brew bottle apache-arrow

      - uses: actions/upload-artifact@main
        if: always()
        with:
          name: arrow-bottle
          path: apache-arrow*.tar.gz

      - run: brew uninstall apache-arrow

      - run: brew install ./apache-arrow*.tar.gz

      - run: file "$(brew --prefix apache-arrow)/lib/libarrow_acero.so"*

      - run: brew install --build-from-source --verbose gdal

      - uses: actions/upload-artifact@main
        if: always()
        with:
          name: logs
          path: logs-*
