name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up Git
        run: |
          git config --global user.email "30379873+carlocab@users.noreply.github.com"
          git config --global user.name "Carlo Cabrera"

          pushd "$(brew --repository)"
          git checkout master
          git fetch origin pull/13648/head:gcc
          git checkout gcc
          git rebase origin/master
          git checkout master
          popd

      - name: Install `hyperfine` for benchmarking
        run: brew install hyperfine

      - name: Install LLVM to audit
        run: brew install llvm

      - name: Time LLVM audit
        env:
          HOMEBREW_SIMULATE_MACOS_ON_LINUX: 1
        run: |
          hyperfine --warmup 1 --export-markdown llvm_orig.md --ignore-failure 'brew audit llvm'
          printf '### LLVM, before:\n' >> "$GITHUB_STEP_SUMMARY"
          cat llvm_orig.md >> "$GITHUB_STEP_SUMMARY"
          printf '\n\n-----\n\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Time tap_syntax test
        env:
          HOMEBREW_SIMULATE_MACOS_ON_LINUX: 1
        run: |
          hyperfine --warmup 1 --export-markdown tap_syntax_orig.md --ignore-failure 'brew audit --tap=homebrew/core --except=version'
          printf '### Tap Syntax, before:\n' >> "$GITHUB_STEP_SUMMARY"
          cat tap_syntax_orig.md >> "$GITHUB_STEP_SUMMARY"
          printf '\n\n-----\n\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Switch to GCC audit PR
        run: git -C "$(brew --repository)" checkout gcc

      - name: Time LLVM audit
        env:
          HOMEBREW_SIMULATE_MACOS_ON_LINUX: 1
        run: |
          hyperfine --warmup 1 --export-markdown llvm_new.md --ignore-failure 'brew audit llvm'
          printf '### LLVM, after:\n' >> "$GITHUB_STEP_SUMMARY"
          cat llvm_new.md >> "$GITHUB_STEP_SUMMARY"
          printf '\n\n-----\n\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Time tap_syntax test
        env:
          HOMEBREW_SIMULATE_MACOS_ON_LINUX: 1
        run: |
          hyperfine --warmup 1 --export-markdown tap_syntax_new.md --ignore-failure 'brew audit --tap=homebrew/core --except=version'
          printf '### Tap Syntax, after:\n' >> "$GITHUB_STEP_SUMMARY"
          cat tap_syntax_new.md >> "$GITHUB_STEP_SUMMARY"
          printf '\n\n-----\n\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Reset `brew`
        run: git -C "$(brew --repository)" reset --hard origin/master

      - name: Time LLVM audit
        env:
          HOMEBREW_SIMULATE_MACOS_ON_LINUX: 1
        run: |
          hyperfine --warmup 1 --export-markdown llvm_orig.md --ignore-failure 'brew audit llvm'
          printf '### LLVM, before:\n' >> "$GITHUB_STEP_SUMMARY"
          cat llvm_orig.md >> "$GITHUB_STEP_SUMMARY"
          printf '\n\n-----\n\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Time tap_syntax test
        env:
          HOMEBREW_SIMULATE_MACOS_ON_LINUX: 1
        run: |
          hyperfine --warmup 1 --export-markdown tap_syntax_orig.md --ignore-failure 'brew audit --tap=homebrew/core --except=version'
          printf '### Tap Syntax, before:\n' >> "$GITHUB_STEP_SUMMARY"
          cat tap_syntax_orig.md >> "$GITHUB_STEP_SUMMARY"
          printf '\n\n-----\n\n' >> "$GITHUB_STEP_SUMMARY"
