name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - run: |
          which -a xattr || exit 0
          xattr=$(which xattr)
          file_xattr=$(file "$xattr")
          echo "$file_xattr"
          <<<"$file_xattr" grep -q 'Mach-O' && exit 0
          cat "$xattr"
