name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  pre_tests:
    name: Pre-test
    runs-on: ubuntu-latest
    outputs:
      out: ${{ steps.first.outputs.out }}
      runners: ${{ steps.first.outputs.runners }}
    steps:
      - id: first
        run: |
          echo "out=true" >> "$GITHUB_OUTPUT"
          echo 'runners=["macos-11", "macos-12", "ubuntu-18.04", "ubuntu-20.04", "ubuntu-22.04"]' >> "$GITHUB_OUTPUT"


  tests:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: pre_tests
    strategy:
      matrix:
        os: ${{fromJson(needs.pre_tests.outputs.runners)}}
        include:
          - os: macos-11
            echo: true
          - os: ubuntu-18.04
            echo: ${{needs.pre_tests.outputs.out}}
      fail-fast: false
    steps:
      - run: echo hello
        if: matrix.echo
      - run: echo world
        if: !matrix.echo
