name: CI
on: [push, workflow_dispatch]

env:
  MESSAGE: "This is a long message, that may contain a [URL](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)."

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        do_deps: [true, false]
    outputs:
      runner: ${{steps.runner.outputs.runner}}
    steps:
      - name: Test outputs
        id: test
        run: |
          printf 'output=hello\n' >> "$GITHUB_OUTPUT"
          printf 'output was ${{steps.test.outputs.output}}\n' | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Another step
        run: |
          printf 'output from previous step was: ${{steps.test.outputs.output}}\n' | tee -a "$GITHUB_STEP_SUMMARY"
          printf "This is a message: %s\n" "$MESSAGE" | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Determine dependent runner
        id: runner
        run: |
          if ${{matrix.do_deps}}
          then
            echo "runner=ubuntu-latest" >> "$GITHUB_OUTPUT"
          fi

  dependent_tests:
    needs: tests
    runs-on: ${{needs.tests.outputs.nonexistent}}
    steps:
      - run: echo hello
