name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  show_installed_frameworks:
    strategy:
      matrix:
        version: [10.15, 11, 12, 13]
    runs-on: macos-${{ matrix.version }}
    steps:
      - run: |
          printf '### `ls -la /Library/Frameworks` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(ls -la /Library/Frameworks)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - run: mv /Library/Frameworks/Mono.framework /tmp

  record_pull_number:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Save pull request number
        env:
          PR: ${{github.event.number}}
        run: |
          mkdir -p pr
          echo "$PR" > pr/number

      - uses: actions/upload-artifact@v3
        with:
          name: pull-number
          path: pr

  outputs_test:
    runs-on: ubuntu-latest
    steps:
      - id: many-outputs
        run: |
          echo "out=foo" >> "$GITHUB_OUTPUT"
          echo "out=bar" >> "$GITHUB_OUTPUT"
          echo "out=baz" >> "$GITHUB_OUTPUT"

      - run: echo '${{ steps.many-outputs.outputs.out }}'

  tests:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    steps:
      - name: Test `if`
        if: ${{
            true &&
            true &&
            !false
          }}
        run: echo it worked!

      - name: Show `gh version`.
        run: |
          printf '### `gh version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(gh version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Show `gh pr merge --help`.
        run: |
          printf '### `gh pr merge --help` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(gh pr merge --help)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
