name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: Test Xcode
    runs-on: macos-11
    strategy:
      matrix:
        xcode: ['13.2.1', '13.1', '13.0', '12.5.1', '12.4', '11.7']
      fail-fast: false
    steps:
      - name: Show `xcode-select -p`
        run: xcode-select -p

      - name: Switch to Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - name: Show `xcode-select -p` after switch
        run: xcode-select -p

      - name: Check `-no_fixup_chains` flag
        run: |
          cat <<EOS > test.c
            int main(){}
          EOS
          clang -Wl,-v -Wl,-no_fixup_chains test.c
