name: CI
on: push

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$GITHUB_REF"
          echo '${{ github.ref }}'

      - run: echo 'variable=foo' >> "$GITHUB_ENV"

      - run: echo "$variable"
