name: CI
on: push

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:main
    env:
      HOMEBREW_DOWNLOAD_CONCURRENCY: 8
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true
          cask: false
          test-bot: false

      - run: echo "HOMEBREW_NO_INSTALL_FROM_API=1" >>"${GITHUB_ENV}"

      - run: brew config

      - run: |
          cd "$(brew --repository homebrew/core)"
          git fetch origin pull/230525/head:bump-eza-0.23.0
          git checkout bump-eza-0.23.0

      - run: brew install --only-dependencies eza

      - run: brew install --build-from-source eza

      - run: |
          touch hello
          eza

      - run: brew test --verbose eza
