name: CI
on: push

jobs:
  test:
    runs-on: macos-${{ matrix.macos-version }}
    strategy:
      fail-fast: false
      matrix:
        macos-version: [13, 14, 15]
        include:
          - macos-version: 13
            xcode: '15.2'
          - macos-version: 13
            xcode: '14.3.1'
          - macos-version: 14
            xcode: '16'
          - macos-version: 14
            xcode: '15.4'
          - macos-version: 14
            xcode: '14.3.1'

    steps:
      - name: Switch Xcode version
        if: matrix.xcode != ''
        env:
          XCODE_VERSION: ${{ matrix.xcode }}
        run: |
          sudo xcode-select --switch "/Applications/Xcode_${XCODE_VERSION}.app/Contents/Developer"

      - name: Print ld version info
        run: |
          echo '```' >> "${GITHUB_OUTPUT}"
          ld -v | tee -a "${GITHUB_OUTPUT}"
          echo '```' >> "${GITHUB_OUTPUT}"

      - name: Write test C file
        run: |
          cat <<'SOURCE' > test.c
            int main(){}
          SOURCE

      - name: Install LLVM
        run: brew update && brew install llvm

      - name: Compile `test.c`
        run: |
          echo '```' >> "${GITHUB_OUTPUT}"
          clang -v test.c -L"$(brew --prefix llvm)/lib" -o test 2>&1 | tee -a "${GITHUB_OUTPUT}"
          echo '```' >> "${GITHUB_OUTPUT}"

      - name: Check `test` linkage
        run: |
          echo '```' >> "${GITHUB_OUTPUT}"
          otool -L ./test | tee -a "${GITHUB_OUTPUT}"
          echo '```' >> "${GITHUB_OUTPUT}"

