name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Install `hyperfine`
        run: brew install hyperfine

      - name: Benchmark `tap_syntax`
        env:
          HOMEBREW_SIMULATE_MACOS_ON_LINUX: 1
        run: |
          hyperfine --warmup 1 \
                    --export-markdown result.md \
                    --ignore-failure \
                    --parameter-list except 'version\,deps,version' \
                    'brew audit --tap=homebrew/core --except={version}'
          mv result.md "$GITHUB_STEP_SUMMARY"
