name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  tests:
    name: GitLab Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, ubuntu-20.04, ubuntu-22.04]
        curl: [system, homebrew]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Install Homebrew Curl
        if: matrix.curl == 'homebrew'
        run: brew install curl

      - name: Prepend `/usr/bin` to `PATH`
        if: matrix.curl == 'system'
        run: printf '/usr/bin:%s\n' "${PATH}" >> "${GITHUB_PATH}"

      - name: Check checksum
        run: |
          URL=https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.4.1/SVT-AV1-v1.4.1.tar.bz2
          CHECKSUM="$(curl -L "$URL" | shasum -a 256 | cut -f1 -d' ')"
          printf '```\n%s\n```\n' "${CHECKSUM}" >> "${GITHUB_OUTPUT}"
