name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Checkout `llvm` PR.
        run: |
          push "$(brew --repository homebrew/core)"
          git fetch origin pull/106925/head:llvm-15
          git checkout llvm-15
          git status
          git rev-parse HEAD
          popd

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Install `llvm` dependencies.
        run: brew install --only-dependencies --build-from-source llvm

      - name: Set up `logs` directory.
        run: |
          mkdir -p logs
          printf 'HOMEBREW_LOGS=%s\n' "$(pwd)/logs" >> "$GITHUB_ENV"

      - name: Build `llvm`.
        run: brew install --build-from-source llvm

      - name: Upload logs.
        uses: actions/upload-artifact@v3
        if: always()
        with:
          path: logs
