name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Check output of `sw_vers`.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
      fail-fast: false
    steps:
      - name: Run `sw_vers`
        run: sw_vers -productVersion
