name: CI
on: push

jobs:
  debug:
    runs-on: macos-latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: true

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew tap shivammathur/php

      - run: |
          cd "$(brew --repo shivammathur/php)"
          git fetch origin pull/1849/head
          git checkout FETCH_HEAD

      - run: brew install --build-bottle --verbose --debug shivammathur/php/php@8.3

      - run: otool -l "$(brew --prefix shivammathur/php/php@8.3)/bin/php"
        if: always()

      - run: brew bottle --verbose --debug shivammathur/php/php@8.3
