name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1
  FORMULA: emscripten

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Show `brew --version`.
        run: |
          printf '### `brew --version` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew --version)" | tee -a "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Install GCC.
        run: brew install gcc

      - name: Link `glibc`.
        run: brew link --force glibc

      - name: Test GCC.
        run: |
          cat <<EOS > test.c
            int main(void) { return 0; }
          EOS
          "$(brew --prefix gcc)/bin/gcc-12" test.c -lc
          ./a.out

      - name: Test GCC again.
        run: |
          cat <<EOS > test.c
            #include <stdio.h>
            int main(void) {
              printf("hello!\n");
              return 0;
            }
          EOS
          "$(brew --prefix gcc)/bin/gcc-12" test.c -lc
          ./a.out

      - name: Check ld.so.conf and related files
        run: |
          etc="$(brew --prefix)/etc"
          ls -la "$etc"
          cat "${etc}/ld.so.conf"
          ls -la "${etc}/ld.so.conf.d"
          cat "${etc}/ld.so.conf.d"/*

      - name: Check binutils linkage
        run: brew linkage binutils

      - name: Use `ldd`.
        run: |
          ld="$(brew --prefix binutils)/bin/ld"
          ldd "${ld}"
          "$(brew --prefix glibc)/bin/ldd" "${ld}"
