name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Try to link with `libcrypto`
        run: |
          export PATH="$(brew --prefix llvm)/bin:${PATH}"
          clang -fuse-ld=lld -xc - -Wl,-v,-L/usr/lib,-lcrypto <<'EOS'
            int main() {}
          EOS
          command -v otool > /dev/null && otool -L ./a.out
          ./a.out
