name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Show `v8` dep tree
        run: |
          printf '### `brew deps --tree v8` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew deps --tree v8)"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Show `v8` dep tree (with test dependencies)
        run: |
          printf '### `brew deps --tree --include-test --annotate v8` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew deps --tree --include-test --annotate v8)"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Show `v8` dep tree (with build dependencies)
        run: |
          printf '### `brew deps --tree --include-build --annotate v8` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew deps --tree --include-build --annotate v8)"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"

      - name: Show `v8` dep tree (with all dependencies)
        run: |
          printf '### `brew deps --tree --include-build --include-test --annotate v8` output\n' >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$(brew deps --tree --include-build --include-test --annotate v8)"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
