name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Benchmark `brew doctor`
    runs-on: ubuntu-latest
    steps:
      - name: Install GCC dependents
        run: |
          brew update
          brew ruby <<EOS > gcc_dependents.txt
          require 'formula'
          gcc_dependents = Formula.all.select do |f|
            next false unless f.tap&.core_tap?

            f.deps.map(&:name).include? "gcc"
          end
          puts gcc_dependents.sample(75).sort_by(&:name)
          EOS

          # We picked a random bunch of formulae, so we may install conflicting ones.
          xargs brew install --force <gcc_dependents.txt || true

          cat gcc_dependents.txt

      - name: List installed formulae
        run: brew list --formulae

      - name: Benchmark
        run: |
          brew install hyperfine

          hyperfine --warmup 1 --export-markdown orig.md --ignore-failure 'brew doctor'

          pushd "$(brew --repository)"
          git fetch origin pull/13639/head:gcc-deps-doctor
          git checkout gcc-deps-doctor
          popd

          hyperfine --warmup 1 --export-markdown new.md --ignore-failure 'brew doctor'

          echo '## Before' >> "$GITHUB_STEP_SUMMARY"
          cat orig.md >> "$GITHUB_STEP_SUMMARY"
          echo '## After' >> "$GITHUB_STEP_SUMMARY"
          cat new.md >> "$GITHUB_STEP_SUMMARY"
