name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
      options: --user=linuxbrew
    timeout-minutes: 360
    env:
      HOMEBREW_LOGS: ${{ github.workspace }}/logs
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - run: |
          cd "$(brew --repository homebrew/core)"
          gh pr checkout 134428
        env:
          GH_TOKEN: ${{ github.token }}

      - run: brew install --build-bottle apache-arrow

      - run: file "$(brew --prefix apache-arrow)/lib/libarrow_acero.so"*

      - run: brew bottle apache-arrow

      - run: |
          brew uninstall apache-arrow
          brew install ./apache-arrow*.tar.gz

      - run: file "$(brew --prefix apache-arrow)/lib/libarrow_acero.so"*

      - run: brew install --build-from-source gdal

      - uses: actions/upload-artifact@main
        if: always()
        with:
          path: logs
