name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Check out `libwhich`
        run: |
          brew install carlocab/personal/libwhich
          if [[ "$(uname)" = Darwin ]]
          then
            LIBEXT=dylib
          else
            LIBEXT=so
          fi
          libwhich libssl.$LIBEXT
          libwhich libcrypto.$LIBEXT
