name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Install `postgresql@14`
        run: brew install postgresql@14

      - name: Show postgres lib dir
        run: pg_config --libdir

      - name: Show postgres include dir
        run: pg_config --cppflags

      - name: Show postgres cflags
        run: pg_config --cflags

      - name: Show postgres ldflags
        run: pg_config --ldflags
