name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
        gcc: [6, 7, 8, 9, 10, 11, 12]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout `master`
        run: git -C "$(brew --repository)" checkout master

      - name: Install `gcc@${{ matrix.gcc }}`
        run: brew install gcc@${{ matrix.gcc }}

      - name: Show `gcc-${{ matrix.gcc }} -print-multiarch`
        run: |
          GCC="gcc-${{ matrix.gcc }}"
          MULTIARCH="$($GCC -print-multiarch)"
          if [[ -n "$MULTIARCH" ]]
          then
            OUTPUT="$MULTIARCH"
          else
            OUTPUT="blank!"
          fi
          printf '### `%s -print-multiarch` output\n' "$GCC" >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
          printf '%s\n' "$OUTPUT" >> "$GITHUB_STEP_SUMMARY"
          printf '```\n' >> "$GITHUB_STEP_SUMMARY"
