name: CI
on: push

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:main
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true
          cask: false
          test-bot: false

      - name: Simulate merge conflict
        run: |
          cd "$(brew --repository homebrew/core)"
          git config --global user.email "github@carlo.cab"
          git config --global user.name "Carlo Cabrera"
          git checkout -b old-main 4f8215e39463753cc71d78650f021112eb776ff2
          git checkout -b feature f3ecdbd01a5bdf94430d4f974b27525f8e56045e

      - name: Do the stuff
        env:
          BOTTLE_LINE_REGEX: '^\s?\+\s*sha256.*:\s+"[a-f0-9]{64}"'
          AWK_SCRIPT: |
            /^\+\+<<<<<<< / {inconflict=1; next}
            /^\+\+=======/ {next}
            /^\+\+>>>>>>> / {inconflict=0; next}
            inconflict
        run: |
          GIT_DIFF="$(git diff)"
          cat <<DIFF >diff.md
          \`\`\`diff
          ${GIT_DIFF}
          \`\`\`
          DIFF

          HUNKS_WITHOUT_CONFLICT_MARKERS="$(awk "${AWK_SCRIPT}" <<<"${GIT_DIFF}")"

          resolvable=false
          if ! grep --extended-regexp --invert-match --quiet "${BOTTLE_LINE_REGEX}" <<<"${HUNKS_WITHOUT_CONFLICT_MARKERS}"
          then
            resolvable=true
          fi
          echo "resolvable=${resolvable}" >>"${GITHUB_OUTPUT}"

          cat diff.md
