name: CI
on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: curl -O https://www.python.org/ftp/python/3.13.0/python-3.13.0-macos11.pkg
      - run: |
          # create installer choice changes to customize the install:
          #    enable the PythonTFramework-3.13 package
          #    while accepting the other defaults (install all other packages)
          cat > ./choicechanges.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <array>
                  <dict>
                          <key>attributeSetting</key>
                          <integer>1</integer>
                          <key>choiceAttribute</key>
                          <string>selected</string>
                          <key>choiceIdentifier</key>
                          <string>org.python.Python.PythonTFramework-3.13</string>
                  </dict>
          </array>
          </plist>
          EOF
      - run: |
          sudo installer -pkg ./python-3.13.0-macos11.pkg \
                         -applyChoiceChangesXML ./choicechanges.plist \
                         -target /
      - run: rm -f python-3.13.0-macos11.pkg
      - run: |
          printf '### Python Framework Directory Layout\n' >>"${GITHUB_STEP_SUMMARY}"
          printf '```\n' >>"${GITHUB_STEP_SUMMARY}"
          ls -lRa /Library/Frameworks/Python.framework | tee -a "${GITHUB_STEP_SUMMARY}"
          printf '```\n' >>"${GITHUB_STEP_SUMMARY}"

      - run: |
          printf '### `/usr/local` Directory Layout\n' >>"${GITHUB_STEP_SUMMARY}"
          printf '```\n' >>"${GITHUB_STEP_SUMMARY}"
          ls -lRa /usr/local | tee -a "${GITHUB_STEP_SUMMARY}"
          printf '```\n' >>"${GITHUB_STEP_SUMMARY}"
