name: CI
on: 
  workflow_dispatch:
    inputs:
      message:
        description: "The message to send"
        required: false

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test message input
        run: |
          echo '${{inputs.message && format('Your message: {0}', inputs.message) || 'You did not input a message :('}}'
