name: CI
on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    container:
      image: ghcr.io/homebrew/ubuntu${{ matrix.container }}:master
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        container: [16.04, 22.04]
      fail-fast: false
    steps:
      - name: Try to reproduce error
        run: |
          [[ -f /proc/1/cgroup ]] && echo yes || echo no
          grep -qE "actions_job|docker" /proc/1/cgroup && echo yes || echo no

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
