name: CI
on: push

jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "/home/linuxbrew/.linuxbrew/bin" >> "${GITHUB_PATH}"

      - run: brew update

      - run: brew config

      - run: brew install gcc

      - run: |
          touch test.c
          gcc-13 test.c
