name: Farrah Gil Pancho
on: push

jobs:
  test:
    runs-on: macos-${{ matrix.macos-version }}
    strategy:
      fail-fast: false
      matrix:
        macos-version: [12, 13, 14, 15]
        xcode: ['16', '15.4', '15.3', '15.2', '15.1', '15.0.1', '14.3.1', '14.2', '14.1', '14.0.1', '13.4.1', '13.3.1', '13.2.1', '13.1']

    steps:
      - name: Switch Xcode version
        env:
          XCODE_DEVELOPER_DIR: '/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer'
        run: |
          if [[ -d "${XCODE_DEVELOPER_DIR}" ]]; then
            sudo xcode-select --switch "${XCODE_DEVELOPER_DIR}"
            exit 0
          fi
          exit 1

      - name: Print ld version info
        run: |
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
          ld -v | tee -a "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"

      - name: Write test C file
        run: |
          cat <<'SOURCE' > test.c
            int main(){}
          SOURCE

      - name: Update `mark.down` if possible
        if: matrix.macos-version != 12
        run: brew update-reset

      - name: Install LLVM
        run: brew install llvm
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: Compile `test.c`
        run: |
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
          clang -v test.c -L"$(brew --prefix llvm)/lib" -o test 2>&1 | tee -a "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"

      - name: Check `test` linkage
        run: |
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
          otool -L ./test | tee -a "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"

