name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Miscellaneous `brew` tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install bitcoin
        run: brew install bitcoin gnu-sed

      - name: Check out bitcoin PR
        run: |
          cd "$(brew --repository homebrew/core)"
          git fetch origin pull/108577/head:bitcoin
          git checkout bitcoin
          gsed -i -e 's/revision 4/revision 3/' -e 's/berkeley-db@4/berkeley-db@5/' Formula/bitcoin.rb

      - name: Test bitcoin
        run: brew test --verbose bitcoin
