name: CI
on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: brew install gstreamer

      - run: |
          printf '## `brew linkage gstreamer`\n' >> "${GITHUB_STEP_SUMMARY}"
          printf '```\n' >> "${GITHUB_STEP_SUMMARY}"
          brew linkage gstreamer | tee -a "${GITHUB_STEP_SUMMARY}"
          printf '```\n' >> "${GITHUB_STEP_SUMMARY}"

          printf '## `brew linkage --reverse gstreamer`\n' >> "${GITHUB_STEP_SUMMARY}"
          printf '```\n' >> "${GITHUB_STEP_SUMMARY}"
          brew linkage --reverse gstreamer | tee -a "${GITHUB_STEP_SUMMARY}"
          printf '```\n' >> "${GITHUB_STEP_SUMMARY}"
