name: CI
on: push

defaults:
  run:
    shell: bash -xeuo pipefail {0}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:main
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true
          test-bot: true

      - name: Set `HOMEBREW_NO_INSTALL_FROM_API`
        run: echo "HOMEBREW_NO_INSTALL_FROM_API=1" >>"${GITHUB_ENV}"

      - run: brew update

      - run: git -C "$(brew --repository)" show HEAD

      - name: Remove `return` in opencv test block
        run: |
          cd "$(brew --repository homebrew/core)"
          sed -i 's/return if OS.linux? || Hardware::CPU.intel?/return if false/' Formula/o/opencv.rb
          echo "HOMEBREW_NO_AUTO_UPDATE=1" >>"${GITHUB_ENV}"
        env:
          GH_TOKEN: ${{ github.token }}

      - run: brew uninstall --force opencv

      - run: brew test-bot --only-formulae opencv
